# Generated by Django 3.0.3 on 2021-09-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.ImageField(upload_to='myphoto')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
